=== tabl1/PW-Proiect/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume,prenume,varsta,adresa,educatie,aptitudini,experienta)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT educatie (#PCDATA)>
<!ELEMENT aptitudini (#PCDATA)>
<!ELEMENT experienta (companie)>
<!ELEMENT companie (#PCDATA)>
<!ATTLIST persoana id CDATA #REQUIRED>

=== tabl1/PW-Proiect/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">

<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Porumbel</strada>
            <numar>7</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <educatie>facultate</educatie>
        <aptitudini>C++</aptitudini>
        <experienta>
            <companie>Bitdefender</companie>
        </experienta>
    </persoana>
    <persoana id="2">
        <nume>Adam</nume>
        <prenume>Iasmina</prenume>
        <varsta>21</varsta>
        <adresa>
            <strada>Primaverii</strada>
            <numar>14</numar>
            <localitate>Vaslui</localitate>
            <judet>Vaslui</judet>
            <tara>Romania</tara>
        </adresa>
        <educatie>liceu</educatie>
        <aptitudini>innot</aptitudini>
        <experienta>
            <companie>Amazon</companie>
        </experienta>
    </persoana>
    <persoana id="3">
        <nume>Ciosnar</nume>
        <prenume>Dragos</prenume>
        <varsta>22</varsta>
        <adresa>
            <strada>Halauceanu</strada>
            <numar>1</numar>
            <localitate>Vama</localitate>
            <judet>Suceava</judet>
            <tara>Romania</tara>
        </adresa>
        <educatie>facultate</educatie>
        <aptitudini>C#</aptitudini>
        <experienta>
            <companie>Centric</companie>
        </experienta>
    </persoana>
</persoane>
